document.writeln('<li id="recent-posts-2" class="widget widget_recent_entries">		<h4>近期文章</h4>	<ul>');
document.writeln('					<li>');
document.writeln('				<a href="http://sigtuma.com/?p=124\">效率最低的联系方式</a>');
document.writeln('						</li>');
document.writeln('					<li>');
document.writeln('				<a href=\http://sigtuma.com/?p=109\">用声音充电?</a>');
document.writeln('						</li>');
document.writeln('					<li>');
document.writeln('				<a href="http://sigtuma.com/?p=97\">所谓藏头诗</a>');
document.writeln('						</li>');
document.writeln('					<li>');
document.writeln('				<a href="http://sigtuma.com/?p=90\">在侧边栏随机显示电影台词</a>');
document.writeln('						</li>');
document.writeln('					<li>');
document.writeln('				<a href="http://sigtuma.com/?p=84\">默哀</a>');
document.writeln('						</li>');
document.writeln('					<li>');
document.writeln('				<a href="http://sigtuma.com/?p=81\">问禅师之码农版</a>');
document.writeln('						</li>');
document.writeln('					<li>');
document.writeln('				<a href=\"http://sigtuma.com/?p=73\">写实的热门电视剧们</a>');
document.writeln('						</li>');
document.writeln('					<li>');
document.writeln('				<a href="http://sigtuma.com/?p=69\">没能去参与救援，献点血也算出份力吧</a>');
document.writeln('						</li>');
document.writeln('				</ul>');
document.writeln('						</li>');